# Generated by Django 3.2.8 on 2022-08-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Shoes', 'Shoes'), ('Watch', 'Watch'), ('Top Wear', 'Top Wear'), ('Down Wear', 'Down Wear')], max_length=30),
        ),
    ]
